apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nm
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-image:v3
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        volumeMounts:
        - name: persistent-volume-backend
          mountPath: /app/app-mount
        - name: db-secrets
          mountPath: /etc/secrets
          readOnly: true
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: persistent-volume-backend
        persistentVolumeClaim:
          claimName: backend-pvc
      - name: db-secrets
        secret:
          secretName: db-secret
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - backend
            topologyKey: "kubernetes.io/hostname"    
      
---
#svc
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: nm
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

