
# This is a basic workflow to help you get started with Actions
#this is for backend #django
name: cfa
on:
  push:
    branches: 
       - nandigama_sharmila_githubactions_basic
       - production
       - staging
env:
  IMAGE_NAME: cfa-image
  IMAGE_TAG: ${{ github.run_number }}
jobs:
  code_checkout_build:
    runs-on: ubuntu-latest
    env:
      name: ${{ 
        github.ref == 'refs/heads/nandigama_sharmila_githubactions_basic' && 'dev' ||
        github.ref == 'refs/heads/prod' && 'production' ||
        github.ref == 'refs/heads/uat' && 'staging' }}
    steps: 
    - name: code-checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
         python-version: 3.11
    - name: installing_requirements
      run: |
        pip install -r backend/requirements.txt
        pip install pylint pytest
    - name: lint_test
      run: pylint backend/backend/ --fail-under=8
    - name: docker_build
      run: |
        docker build -f backend/admin_service.dockerfile -t $IMAGE_NAME:$IMAGE_TAG backend/
        docker save -o $IMAGE_NAME.tar  $IMAGE_NAME:$IMAGE_TAG
    - name: artifact_upload
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG}}
        path: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG}}.tar
        
        
        
  
  

  

      
      
      
 
